name: ci-golang
on:
  pull_request:
    branches:
      - develop
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.26, 1.25]
    steps:
      - uses: actions/checkout@v6
      - name: Set up Go version ${{ matrix.go-version }}
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run math
        run: go run math.go
      - name: Test
        run: go test -v

  check-app:
    if: always()
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [ "${{ needs.test.result }}" = "failure" ]; then
            exit 1
          fi
